### ISSUE TITLE
Unable to import images

### ISSUE THREAD

**Issue by loftiskg** [NeuroMorph-EPFL/NeuroMorph#3]
Hello,

I am trying to import the sample stack of images that were posted in the Data directory, however it is throwing me a weird error.  Here is step by step what I am doing.

1. I first opened up the blender file that I downloaded from this repository:
![capture1](https://user-images.githubusercontent.com/8094134/38280959-0302e56e-375d-11e8-8a11-48561e5c6af8.PNG)

2.  Then I selected the directory that I wanted to be the source of the Z-source port
![capture2](https://user-images.githubusercontent.com/8094134/38280986-397f8052-375d-11e8-88ee-6ad19c62a239.PNG)

3. I selected the folder and it returned to the 3d view, now with the red stack ladder present.
![capture4](https://user-images.githubusercontent.com/8094134/38281017-5d36a368-375d-11e8-8417-ae44bcff67ee.PNG)

4.  Finally to visualize the images I hit the button 'Show Images(s) at Vertex'  and it gave me the following error shown in the image below
![capture5](https://user-images.githubusercontent.com/8094134/38281043-87ceb2c8-375d-11e8-9f1e-23ec0e662e3f.PNG)

Any thoughts on why this is happening?

Thank you!

**Comment by ajorstad** [comment]
Hi-

Yes, you need to select a vertex (from Edit mode) before clicking on "Show Image(s) at Vertex", in order for the tool to know which image to display.  For future reference, we have tried to provide basic instructions in the tooltip that displays when you hover over a button, in addition to the documentation on the Blender wiki, but if the provided documentation is insufficient, feel free to always contact us for help.

Hope the NeuroMorph tools are useful for you!

**Comment by loftiskg** [comment]
Great!  That did the trick, thank you!
