### ISSUE TITLE
Cannot view stack images in Cycles render

### ISSUE THREAD

**Issue by loftiskg** [NeuroMorph-EPFL/NeuroMorph#4]
Hello,

I am trying to render the stack images using blender cycles.  The images display on the plane connected to the stack ladder in the viewport and when I render using Blender Render, however; the plane is blank when I render with Cycles.  Any thoughts on how to go about resolving this?  I feel like it is something simple, but the solution is eluding me.

Thank you in advance!

**Comment by ajorstad** [comment]
Hi - There is an "Include images in render" checkbox in the 3D Drawing tool that must be checked in order for the images to be rendered.  I have not checked this functionality with the most recent version of Blender, so it's possible that it no longer works, but it did at some point!

**Comment by ajorstad** [comment]
I am not sufficiently familiar with how Cycles rendering works, so I'm afraid I can't help you there.  What we had to do for the Blender Render was to create plane objects with texture materials, which is a bit slower than the "empty" objects we normally use for the images, but empties are not rendered.  You can try to follow the "render_images" variable through the code to see if any of the modifications might need further development for Cycles.  Apparently the [Materials Utils](https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/3D_interaction/Materials_Utils) tool converts regular Blender materials and textures for use in Cycles, so maybe that might help?

If/when you figure it out, do let us know!

**Comment by ajorstad** [comment]
Since the update to Blender 2.8+, images are now loaded as texture materials on mesh planes, and they display correctly in the render, so this issue is now resolved.
